spring.application.name=sb-ecom
spring.h2.console.enabled=true
spring.datasource.url = jdbc:h2:mem:test
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.Format_sql = true;

spring.h2.console.path=/mydb

project.image=images/

spring.app.jwtSecret =z9Qm8vL2kP7xR1sT5nY6cD3hJ8aB4uW9qM0eF2gH1kL3pR6tS8vN5xC7yZ0dA1b
spring.app.jwtExpirationMs =300000000
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.example.securitydemo=DEBUG
logging.level.com.ecommerce.project=DEBUG
spring.ecom.app.jwtCookie=springBootEcom